FROM golang:1.18.3

WORKDIR /go/src

RUN apt-get update && apt-get install -y \
    curl \
    python3-pip \
    vim

RUN pip3 install 'mtools[mloginfo]'
RUN pip3 install python-dateutil
RUN go install github.com/cosmtrek/air@latest
COPY go.mod go.sum ./
RUN go mod download

CMD ["tail", "-f", "/dev/null"]
